### PR TITLE
Dropdown menu link

### PR DESCRIPTION
**Pull request by nettle790**
issue#73

linked dropdown-menu to lifestyle.html file.boilerplate added to lifestyle.html page.

### CODE REVIEW

**Review by IsthisSid — CHANGES_REQUESTED** [review]
@nettle790 Tested 👍🏻. Please remove the link for 'The Daily Tackles' and resubmit with your changes. We are only working on 'The Road to a Healthy Lifestyle' for this ticket. Once you're done, I can merge.

**Comment by nettle790** [comment]
Ok

**Comment by nettle790** [comment]
issue #78
delinked  the daily tackles dropdown menu option from lifestyle.html files.

**Comment by nettle790** [comment]
happy to help.

**Pull request merged**
